{"status": "resolved", "priority": "bug", "title": "Fixes for failures in customs tests", "milestone": "", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "111", "files": [{"url": "http://openhatch.org/bugs/file52/fix_TracBug_tests.patch", "author": "pythonian4000"}, {"url": "http://openhatch.org/bugs/file47/fixes_for_customs_tests_TracBug_and_BugzillaTests.patch", "author": "pythonian4000"}], "history": [{"message": "All the customs tests now pass. Yippee!\n   \n", "author": "paulproteus"}, {"message": "Pushed, and kicking off a new Hudson run:\n\n<a href=\"http://linode2.openhatch.org:8080/job/Test%20the%20%22customs%22%20app/\">http://linode2.openhatch.org:8080/job/Test%20the%20%22customs%22%20app/</a>\n   \n", "author": "paulproteus"}, {"message": "Whoops! The TracBug tests are failing at present due to two reasons:\n\n- I forgot to remove the 'bitesized_keyword' argument that is no longer used.\n\n- 'as_data_dict_for_bug_object()' requires an argument of a function that\nextracts bug tracker specific data, like the bitesized keyword. This needs to be\npassed in by the test.\n\nThe new patch fixes these issues.\n   \n", "author": "pythonian4000"}, {"message": "Thanks Jack!\n\nI'm kicking off a new test run:\n<a href=\"http://linode2.openhatch.org:8080/job/Test%20the%20%22customs%22%20app/\">http://linode2.openhatch.org:8080/job/Test%20the%20%22customs%22%20app/</a>\n\nLet's see how far we've gotten, and how far we have to come.\n   \n", "author": "paulproteus"}, {"message": "This is a general bug for the various failures and errors in the customs tests.\n\nSpeaking of which: attached is a patch for some of these failures and errors,\nspecifically in the TracBug and BugzillaTests classes.\n   \n", "author": "pythonian4000"}]}