{"status": "resolved", "priority": "bug", "title": "Stopping the bug importer breaking on various URLErrors", "milestone": "0.11.01", "superceder": "", "nosylist": ["paulproteus, pythonian4000"], "assigned": "", "waitingon": "", "keywords": [], "id": "121", "files": [{"url": "http://openhatch.org/bugs/file64/add_URLError_catches_to_bug_importer.patch", "author": "pythonian4000"}, {"url": "http://openhatch.org/bugs/file61/google_importer_403_catch.patch", "author": "pythonian4000"}], "history": [{"message": "This has been sitting for far too long, and the file the patches affect (which I\nbelieve has been patched) will be modified soon when Twisted meets the\nimporters. So marking as resolved.\n   \n", "author": "pythonian4000"}, {"message": "Hey, Jack, did I let this rot for too long? I can't find a revision it applies \nagainst, even if I go back in time.\n\nBut it looks like I merged them already. If you agree, please set the status to \n\"resolved\".\n   \n", "author": "paulproteus"}, {"message": "I would like this patch to be more specific about the errors that it silences.\n\n408 is an interesting one! Can you add a commit on top of this that makes it \nonly silence HTTP 408, and any other errors it needs to, it should do \nexplicitly?\n\nI (oops) recklessly already pushed this to origin/master, but please add a \ncommit on top that makes it more specific.\n   \n", "author": "paulproteus"}, {"message": "I have gone through and added some more URLError catches to the bug importer,\nbecause a few of them were throwing URL Timeout errors. This is so that the bug\nimporter doesn't break on a single error but gets as many bugs refreshed as it\ncan. The errors are sent to logging.error, and I gather that paulproteus wants\nto get these logs on the web.\n\nApply this patch after the google one.\n   \n", "author": "pythonian4000"}, {"message": "Google Code allows you to set a project as being private, so only viewable to\nauthorized people. How this affected us is that one of the Google Code projects\nthat we track, the Fifty State Project, has very recently gone private for some\nunknown reason, and the bug importer couldn't get anything from it -&gt; it broke.\n\nThis patch adds a catch that prevents the bug importer from breaking and outputs\na message to logging.error (so when we eventually log these messages we can\neasily check for problem trackers). There are also a couple of tests.\n   \n", "author": "pythonian4000"}]}