{"status": "resolved", "priority": "bug", "title": "When hitting an empty CSV, Trac importer crashes", "milestone": "", "superceder": "", "nosylist": ["paulproteus"], "assigned": "", "waitingon": "", "keywords": [], "id": "777", "files": [], "history": [{"message": "This is fixed by\n<a href=\"https://github.com/openhatch/oh-bugimporters/commit/998d85dc604f796676b54df85a4b156be6369ecc\">https://github.com/openhatch/oh-bugimporters/commit/998d85dc604f796676b54df85a4b156be6369ecc</a>\n   \n", "author": "paulproteus"}, {"message": "You can reproduce this with this URL:\n\n<a href=\"https://trac.xiph.org/query?\">https://trac.xiph.org/query?</a>\nstatus=assigned&amp;status=new&amp;status=reopened&amp;order=priority&amp;format=csv&amp;\nkeywords=%7Eeasy\n\nThe end of the stack trace:\n\n\n          File \"/home/deploy/oh-bugimporters/bugimporters/trac.py\", line 160, in \nprocess_bugs\n            self.determine_if_finished()\n          File \"/home/deploy/oh-bugimporters/bugimporters/trac.py\", line 243, in \ndetermine_if_finished\n            self.finish_import()\n          File \"/home/deploy/oh-bugimporters/bugimporters/base.py\", line 124, in \nfinish_import\n            self.rm.maybe_quit()\n   \n", "author": "paulproteus"}]}