{"status": "resolved", "priority": "bug", "title": "Sometimes the app crashes on the location page", "milestone": "", "superceder": "", "nosylist": ["paulproteus, rodney757"], "assigned": "rodney757", "waitingon": "", "keywords": [], "id": "845", "files": [], "history": [{"message": "Resolved with <a href=\"https://github.com/openhatch/oh-\">https://github.com/openhatch/oh-</a>\nmainline/commit/1f5493cd8f51431e62836d157b9535acb4cc469c\n   \n", "author": "paulproteus"}, {"message": "Commented on the pull request!\n   \n", "author": "paulproteus"}, {"message": "\n  <a href=\"https://github.com/openhatch/oh-mainline/pull/109\">https://github.com/openhatch/oh-mainline/pull/109</a>\n\n   \n", "author": "rodney757"}, {"message": "Traceback (most recent call last):\n\n  File \"/home/deploy/milestone-\na.buildout/vendor/packages/Django/django/core/handlers/base.py\", line 111, in \nget_response\n    response = callback(request, *callback_args, **callback_kwargs)\n\n  File \"/home/deploy/milestone-\na.buildout/vendor/packages/Django/django/contrib/auth/decorators.py\", line 23, \nin _wrapped_view\n    return view_func(request, *args, **kwargs)\n\n  File \"/home/deploy/milestone-a.buildout/mysite/account/views.py\", line 305, in \nset_location_do\n    user_profile.latitude = as_dict['latitude']\n\nKeyError: 'latitude'\n\nIt'd be good to reproduce this in the test suite and then fix it.\n   \n", "author": "paulproteus"}]}